@startuml 自動販売機
left to right direction

    state 自動販売機{
        [*] --> 料金投入待ち
        料金投入待ち --> ボタン選択待ち : お金を投入
        ボタン選択待ち --> ドリンク排出中 : ボタンを押す
        ドリンク排出中 --> 料金投入待ち : ドリンクが提供される
        料金投入待ち --> [*]
    }
@enduml