@startuml 診察予約システム
left to right direction
actor 患者 as k
actor 看護師 as ku
rectangle 診察予約システム {
    usecase 予約情報を登録する as t
    usecase 順番を表示する as n
    usecase 予約を確認する as yoyaku
    usecase 予約を取り消す as t1
    usecase 現在の患者番号を一つ増やす as g
}
k --> t
k --> n
k --> yoyaku
k --> t1
g <-- ku

@enduml