@startuml
hide footbox
Actor 会員 as a1
participant "商品検索画面" as boundary
participant "商品検索コントローラ" as control
participant "商品" as entity1
participant "商品カテゴリ" as entity2
activate a1
a1 -> boundary :商品検索（商品番号）
activate boundary
boundary -> control :商品検索（商品番号）
activate control
create entity1
control --> entity1 :<< create >>生成（）
loop 商品カテゴリ数
create entity2
control -->> entity2 :<<< create >> 生成()
activate entity1
deactivate entity1
control -> entity1 :商品カテゴリ設定（）
end loop
control -->> boundary :商品情報
boundary -> boundary :商品情報表示（商品情報）
activate boundary
@enduml