@startuml 診察予約システム
left to right direction

    state メニュー
    state 予約と登録
    state あなたの画面
    state 今の順番
メニュー --> 予約と登録 :　接続する
予約と登録 --> あなたの画面 : 登録ボンタンを押す
あなたの画面 --> メニュー : 登録番号を表示する
予約と登録 --> メニュー : 取消ボンタンを押す
あなたの画面 <-- 予約と登録 : 確認ボタンを押す
メニュー --> 今の順番 : 今の順番を表示する 
今の順番 --> メニュー : 患者番号を一つ増やす
 \
[*] --> メニュー
メニュー -->[*]

@enduml