@startuml
object "<u>Aさん：客</u>" as a{
チェックイン日 = 5月3日
}
object "<u>Bさん：客</u>" as b{
チェックイン日 = 5月3日
}
object "<u>301号室：部屋</u>" as 301{
タイプ = シングル
宿泊料 = 11000
キャンペーン価格 = 9000
キャンペーン期間 = 4月29日~5月6日
}
object "<u>302号室：部屋</u>" as 302{
タイプ = シングル
宿泊料 = 11000
キャンペーン価格 = 9000
キャンペーン期間 = 4月29日~5月6日
}
object "<u>303号室：部屋</u>" as 303{
タイプ = シングル
宿泊料 = 11000
キャンペーン価格 = 9000
キャンペーン期間 = 4月29日~5月6日
}
a -- 301
b -- 303
@enduml