@startuml
hide footbox
Actor 注文係 as a1
participant ":注文登録画面" as boundary
participant ":商品" as entity1
participant ":注文" as entity2
activate a1
a1 ->boundary :確認
activate boundary
boundary -> entity1
activate entity1
entity1 -->>boundary :商品情報
activate entity1
entity1 -> entity1 :商品情報表示
a1 -> boundary :商品発注（注文情報）
activate entity2
boundary -->entity2 
@enduml