@startuml
hide footbox
participant "ログイン:予約画面" as boundary
participant ":ログインコントローラ" as control
activate boundary
 boundary->> control:ログイン()
activate control
control -> control:確認操作()
activate control
@enduml