@startuml
hide footbox
Actor 客 as a1
participant ":フロア店員" as boundary
participant ":料理人" as control
mainframe sd ラーメン屋さん
activate a1
a1 -> boundary :ラーメンを注文する
activate boundary
boundary -> control :料理を指示する
activate control
control -> control :調理をする
control -->> boundary :ラーメン
boundary -->> a1 :ラーメン
@enduml